### ISSUE TITLE
Compile error with Qt 6.2.4

### ISSUE THREAD

**Issue by bhamadicharef** [masc4ii/SysexLive#3]
MainWindow.cpp line 368 if( Rxml.isStartElement() && Rxml.name() == "settings" )

C:\Users\bhama\Downloads\Qt-SysexLive-master\SysexLive\MainWindow.cpp:368: error: invalid conversion from 'const char*' to 'char' [-fpermissive]
In file included from C:/Qt/Qt5.12.6/6.2.4/mingw_64/include/QtCore/qstring.h:50,
                 from C:/Qt/Qt5.12.6/6.2.4/mingw_64/include/QtCore/qobject.h:47,
                 from C:/Qt/Qt5.12.6/6.2.4/mingw_64/include/QtWidgets/qwidget.h:45,
                 from C:/Qt/Qt5.12.6/6.2.4/mingw_64/include/QtWidgets/qmainwindow.h:44,
                 from C:/Qt/Qt5.12.6/6.2.4/mingw_64/include/QtWidgets/QMainWindow:1,
                 from ..\SysexLive\MainWindow.h:11,
                 from ..\SysexLive\MainWindow.cpp:8:
C:/Qt/Qt5.12.6/6.2.4/mingw_64/include/QtCore/qchar.h:126:45: note: candidate: 'constexpr QChar::QChar(char)' (near match)
  126 |     QT_ASCII_CAST_WARN constexpr Q_IMPLICIT QChar(char c) noexcept : ucs(uchar(c)) { }
      |                                             ^~~~~
C:/Qt/Qt5.12.6/6.2.4/mingw_64/include/QtCore/qchar.h:126:45: note:   conversion of argument 1 would be ill-formed:
..\SysexLive\MainWindow.cpp:368:54: error: invalid conversion from 'const char*' to 'char' [-fpermissive]
  368 |         if( Rxml.isStartElement() && (Rxml.name() == "settings") )
      |                                                      ^~~~~~~~~~
      |                                                      |
      |                                                      const char*

**Comment by masc4ii** [comment]
What is the Qt version you use to compile? Your installation looks very strange! It looks you installed v6.2.4 inside a 5.12.6 installation. SysexLive compiles fine with Qt 5.12.6, but will not compile with 6.2.4, because Qt changed the API.

**Comment by bhamadicharef** [comment]
Noted thanks. Yeah never realised that about my configuration!
